import {Book} from "./book";
let libro:Book = new Book("Introduccion a JavaScript", 233, "23444333-BC23333", "Joseph Smith", "Now Editions")
console.log(libro.toString())
console.log(libro.getAuthor())
console.log(libro.setAuthor("Roberto"))
console.log(libro.getTitle())
console.log(libro.setTitle("Ya no puedo más"))
console.log(libro.getNpages())
console.log(libro.setNpages(356))
console.log(libro.getEditorial())
console.log(libro.setEditorial("Codenotch"))
console.log(libro.getIsbn())
console.log(libro.setIsbn("123456"))
