import {Book} from "./book";
let libro:Book = new Book("Introduccion a JavaScript", 233, "23444333-BC23333", "Joseph Smith", "Now Editions")
console.log(libro.toString())
console.log(libro.getAuthor())
libro.setAuthor("Roberto")
console.log(libro.getTitle())
libro.setTitle("Ya no puedo más")
console.log(libro.getTitle())
console.log(libro.getNpages())
libro.setNpages(356)
console.log(libro.getEditorial())
libro.setEditorial("Codenotch")
console.log(libro.getIsbn())
libro.setIsbn("123456")
